version: "3.9"

networks:
  docker.ntw:
    name: docker.ntw
volumes:
  docker.vle:
    name: docker.vle

services:
  db:
    # image: mysql:5.7
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    container_name: mysql.ctr
    networks:
      - docker.ntw
    volumes:
      - docker.vle:/var/lib/mysql
      # - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: db_banco
    ports:
      - 3306:3306
  api:
    build: .
    networks:
      - docker.ntw
    ports:
      - 5000:80
    env_file:
       - .env  
    depends_on:
      - db  
